import AppKit
import ApplicationServices
import Carbon.HIToolbox

/// Puts text into the frontmost app: clipboard + simulated ⌘V, then restores
/// whatever was on the clipboard before.
enum TextInserter {
    enum Outcome { case pasted, copiedOnly }

    /// Clipboard managers that honour nspasteboard.org markers skip our temporary write.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// The user's clipboard while one of our pastes waits to restore it, so a second
    /// paste inside that window restores the original instead of our first transcript.
    private static var pendingRestore: (snapshot: Snapshot, changeCount: Int)?

    @discardableResult
    static func insert(_ text: String, keepInClipboard: Bool) -> Outcome {
        let pasteboard = NSPasteboard.general
        var saved: Snapshot?
        if !keepInClipboard {
            if let pending = pendingRestore, pending.changeCount == pasteboard.changeCount {
                saved = pending.snapshot
            } else {
                saved = snapshot(pasteboard)
            }
        }

        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        if !keepInClipboard {
            pasteboard.setData(Data(), forType: transientType)
            pasteboard.setData(Data(), forType: autoGeneratedType)
        }
        let ourChange = pasteboard.changeCount

        guard Permissions.accessibilityGranted else {
            pendingRestore = nil
            return .copiedOnly
        }
        postCommandV()

        if let saved {
            pendingRestore = (saved, ourChange)
            // Give the target app time to read the clipboard before restoring it.
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                guard pasteboard.changeCount == ourChange else { return }  // copied again since
                pendingRestore = nil
                restore(saved, to: pasteboard)
            }
        }
        return .pasted
    }

    static func copy(_ text: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
    }

    // MARK: - Keystroke

    private static func postCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let key = keyCode(for: "v") ?? CGKeyCode(kVK_ANSI_V)
        for isDown in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: isDown)
            // Explicit flags: the user may still be holding ⌥ from the dictation shortcut.
            event?.flags = .maskCommand
            event?.post(tap: .cgAnnotatedSessionEventTap)
        }
    }

    /// The key that types `character` in the current layout (V is not at the same place on Dvorak).
    private static func keyCode(for character: String) -> CGKeyCode? {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let property = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData)
        else { return nil }
        let layoutData = Unmanaged<CFData>.fromOpaque(property).takeUnretainedValue() as Data
        return layoutData.withUnsafeBytes { raw -> CGKeyCode? in
            guard let layout = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return nil }
            for code in 0..<128 {
                var deadKeys: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                // With ⌘ held: "Dvorak – QWERTY ⌘" maps keys differently under ⌘.
                let commandState = UInt32((cmdKey >> 8) & 0xFF)
                let status = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDisplay), commandState,
                                            UInt32(LMGetKbdType()), OptionBits(kUCKeyTranslateNoDeadKeysBit),
                                            &deadKeys, chars.count, &length, &chars)
                if status == noErr, String(utf16CodeUnits: chars, count: length) == character {
                    return CGKeyCode(code)
                }
            }
            return nil
        }
    }

    // MARK: - Clipboard snapshot

    private typealias Snapshot = [[(NSPasteboard.PasteboardType, Data)]]

    private static func snapshot(_ pasteboard: NSPasteboard) -> Snapshot {
        (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
        }
    }

    private static func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !snapshot.isEmpty else { return }
        let items = snapshot.map { entries in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        pasteboard.writeObjects(items)
    }
}
